### ISSUE TITLE
Manage a pool of connections

### ISSUE THREAD

**Issue by jennings** [jennings/Turbocharged.Beanstalk#2]
Currently the `BeanstalkConnection` object maintains a single connection to Beanstalk. That means it can process messages one at a time, with no cancellation. For example, a "reserve" command blocks all other commands until a job is reserved or the timeout expires (this is how Beanstalk appears to work under the hood).

There could be a new top-level `BeanstalkPool` object which opens new TCP connections to Beanstalk as necessary. Considerations:
- If different users of the pool want to use/watch different pools, does every combination need to get its own connection? One connection can't use multiple tubes, but it would be _possible_ to always preceed a command with a use command for the tube it was meant for. The equivalent of alawys doing this:
  
  ``` c#
  await prod.UseAsync("my-tube");
  await prod.PutAsync(...);
  await prod.UseAsync("my-tube");
  await prod.PutAsync(...);
  ```
- Consumers need to be isolated from producers, or else a "reserve" followed by a "put" could deadlock the connection.

**Comment by chrcao** [comment]
hi, why consumer need to be isolated from producers?
beanstalkd not support that scenario or other reasons?

**Comment by jennings** [comment]
Hi @chrcao!

Beanstalk does support that scenario, but you have to be careful with it.

It has been a while since I worked with Beanstalk, but as I recall, Beanstalk responds to commands in the order they were sent. Let's say a client tried to be a consumer and producer at the same time, and sent these commands:

```
reserve
put 1 0 10 foobar
```

If there are no jobs in the tube for the `reserve`, then the `put` will be ignored until the `reserve` finally receives a job.

That's probably not a great outcome, and it would be easy to make that mistake. So, that's why I feel like a good client library should help the developer avoid accidentally causing that problem.

**Comment by chrcao** [comment]
@jennings thanks for you answer, i got the point.
and another question when I review beanstalkd code. the data type of  job id from beanstalkd is uint64.
in c#, the same capacity data type is ulong. Wil these  cause problem when beanstalkd insert new job and return a job id more bigger than int(using in this client)?

**Comment by jennings** [comment]
Probably! 😄 

Good catch. If you want to create a pull request for that, please do.

**Comment by jennings** [comment]
I no longer think this issue makes sense to do. The caller is perfectly capable of managing the number of connections they create.

But it does make sense to make `BeanstalkConnection` handle reconnection logic. Right now, if you create a worker and the connection dies, the worker dies. That isn't good.
